// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

features {user.lib.arch.big}
package lib.pkg

public specific func message_pkg(): Unit {
    println("Some example message")
}

public specific func message1_pkg(): Unit {
    println("Some example message")
}

